[project]
name = "fly-in"
description = "Fly-in project for 42 Belgium School"
version = "1.0.0"
requires-python = ">=3.10"
readme = "README.md"
authors = [{ name = "mbuchet" }]
dependencies = ["parse"]

[tool.mypy]
exclude = ['^\.venv/']

[[tool.mypy.overrides]]
module = "parse.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
